#!/bin/tcsh
set current_directory = `pwd`
set oss_directory = `dirname ${current_directory}`
cp /home/dev/bin/javalib/ngat_astrometry.jar .
cp /home/dev/bin/javalib/ngat_new_oss.jar .
cp /home/dev/bin/javalib/ngat_new_icm.jar .
cp /home/dev/bin/javalib/ngat_new_phase2.jar .
cp /home/dev/bin/javalib/ngat_new_tcm.jar .
cp /home/dev/bin/javalib/ngat_util.jar .
cp /home/dev/bin/javalib_third_party/log4j-1.2.13.jar .
# Currently used for the currently installed mysql (mysql-5.1.35-linux-i686-glibc23) on the oss machine 
cp /home/dev/bin/javalib_third_party/mysql-connector-java-3.1.12-bin.jar .
# Latest mysql connector from https://dev.mysql.com/downloads/connector/j/
cp /home/dev/bin/javalib_third_party/mysql-connector-j-9.3.0.jar .
cp ${oss_directory}/resources/security/policy.dat .
